//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmSetting
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> parameter1 { get; set; }
        public Nullable<double> parameter2 { get; set; }
        public string parameter3 { get; set; }
        public string parameter4 { get; set; }
        public string parameter5 { get; set; }
        public int State { get; set; }
        public System.DateTime EditTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string EditUser { get; set; }
        public int AlarmTypeID { get; set; }
        public int InOutType { get; set; }
    }
}
