//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int ID { get; set; }
        public Nullable<int> MobileID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string Plate { get; set; }
        public string VehicleSIM { get; set; }
        public string VoiceNum { get; set; }
        public string DataNum { get; set; }
        public string GPRSNum { get; set; }
        public string VehiclePassword { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creater { get; set; }
        public string LoginPass { get; set; }
        public Nullable<int> LoginEnable { get; set; }
        public Nullable<int> IsEnable { get; set; }
        public Nullable<System.DateTime> OverdueTime { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> PswState { get; set; }
        public Nullable<int> OilBox { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ServerID { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<int> Icon { get; set; }
        public string InstallerName { get; set; }
        public string InstallPosition { get; set; }
        public string InstallType { get; set; }
        public Nullable<System.DateTime> InstallTime { get; set; }
        public Nullable<int> Cpys { get; set; }
        public string Sccj { get; set; }
        public string Aliases { get; set; }
        public Nullable<System.DateTime> IsEnableTime { get; set; }
        public string VIN { get; set; }
        public Nullable<int> VehBrandID { get; set; }
        public Nullable<int> VehSeriesID { get; set; }
        public Nullable<int> IPCode { get; set; }
        public string VehicleType { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
        public Nullable<int> VehicleStatus { get; set; }
    }
}
